# Generated by Django 5.2.7 on 2025-10-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_myself',
            field=models.TextField(blank=True, null=True),
        ),
    ]
