# Generated by Django 5.2.5 on 2025-09-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d/')),
            ],
        ),
    ]
