# Generated by Django 5.2.7 on 2025-10-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='menucake',
            name='description_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menucake',
            name='category',
            field=models.ManyToManyField(blank=True, to='menu.flowercategory'),
        ),
    ]
