# Generated by Django 5.2.5 on 2025-10-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_flowercategory_menucake_description_detail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuCake',
            new_name='MenuFlower',
        ),
    ]
